### ISSUE TITLE
Polish the layout and styling

### ISSUE THREAD

**Issue by harryworld** [MindFundStudio/MixablyMac#23]
- [x] Player Control #14 
- [x] Playlist
- [x] Mood list
- [x] Song View
- [x] Mixably View
- [x] Mixably Filter #10
- [x] Logo #32 
- [x] Menu bar icon #32

**Comment by leotumwattana** [comment]
Updated styling and pushed. Will need some more fine tuning, but please
check out what it looks like so far. ;)
