### ISSUE TITLE
MXAnalyseOperation file error

### ISSUE THREAD

**Issue by harryworld** [MindFundStudio/MixablyMac#25]
```
error: Error Domain=MXErrorDomain Code=1 "(null)" UserInfo={location=file:///Users/harryng/Music/iTunes/iTunes%20Media/Music/Compilations/%23Love/2-15%20Marry%20Me.m4a}
```

Refer to #3

**Comment by harryworld** [comment]
It looks like the `blackbox` has a problem in processing file url with `#` sign.
In the process, it generates those csv files and grab the data from it and send to the pipe. However, in the process of creating csv files, it saves to a wrong path, which is parent of the song actual folder.

**Comment by leotumwattana** [comment]
Sent a message to Sacha on Mixably Slack group regarding the # sign issue. Awaiting his response.

**Comment by harryworld** [comment]
Closed via https://github.com/MindFundStudio/MixablyMac/commit/8972eb1ab4973e0afaea1b6b556eb1b03806bb66
