### ISSUE TITLE
Kill border of filtered song list

### ISSUE THREAD

**Issue by cheeech** [MindFundStudio/MixablyMac#44]
- Song List
  - [x] Table Header Border
- Filtered Song
  - [x] Table Header Border
  - [x] Filtered List

**Comment by harryworld** [comment]
Modifying table header
http://stackoverflow.com/questions/32666795/how-do-i-override-layout-of-nstableheaderview
http://stackoverflow.com/questions/4753282/modifying-table-headers-on-mac

CGRectDivide
http://stackoverflow.com/questions/24107892/how-to-call-cgrectdivide
