### ISSUE TITLE
Filter list's songs are missing when filter list view shows up

### ISSUE THREAD

**Issue by josephktcheung** [MindFundStudio/MixablyMac#53]
Introduced in https://github.com/MindFundStudio/MixablyMac/commit/571b0853b601003d402b3976c898fb4077b33f60#diff-f092b3374895cb89e45fd423d042cde3R62

**Comment by josephktcheung** [comment]
@leotumwattana did https://github.com/MindFundStudio/MixablyMac/commit/571b0853b601003d402b3976c898fb4077b33f60#diff-f092b3374895cb89e45fd423d042cde3R62 crash on you?

**Comment by harryworld** [comment]
Is it the default mood?

**Comment by leotumwattana** [comment]
Yes it did. When I ran it, there was no default mood and hence crashed.
