### ISSUE TITLE
"Create Mood" when filter icon is tapped

### ISSUE THREAD

**Issue by cheeech** [MindFundStudio/MixablyMac#56]

**Comment by harryworld** [comment]
What is the bug about?

**Comment by cheeech** [comment]
When you click the filter icon on top right, a pop up for creating new mood...pops up. 

Only happens when in filter mode.

**Comment by harryworld** [comment]
The popover shows when none of the mood is selected, this asks the user to save the current filter settings as a new mood.
If you have already chosen a mood on the left, the popover will not show

**Comment by cheeech** [comment]
Let's talk about this one tomorrow in person.

On Monday, 11 January 2016, Harry Ng notifications@github.com wrote:

> The popover shows when none of the mood is selected, this asks the user to
> save the current filter settings as a new mood.
> If you have already chosen a mood on the left, the popover will not show
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MindFundStudio/MixablyMac/issues/56#issuecomment-170500181
> .

## 

*Mark Cheng *
chenghtmark@gmail.com
+852 61917068  |  [image: Skype] chenghtmark1
 [image: Facebook] http://www.facebook.com/chenghtmark [image: View my
profile on LinkedIn] http://hk.linkedin.com/pub/mark-cheng/31/828/109[image:
Instagram] http://instagram.com/chenghtmark [image: Twitter]
http://www.twitter.com/chenghtmark  https://github.com/miteymouse

**Comment by harryworld** [comment]
Relate to #53
